### ISSUE TITLE
Can I deprecate the pass-through of unknown plugin attributes with hapi v17?

### ISSUE THREAD

**Issue by WesTyler** [hapijs/glue#103]
Glue currently preserves and passes through unknown plugin attributes to the hapi registration method as seen [here](https://github.com/hapijs/glue/blob/master/test/index.js#L312).

According to the hapi tests, these are simply [ignored](https://github.com/hapijs/hapi/blob/master/test/server.js#L368-L404).

Is there any problem with me removing the Hoek.cloneWithShallow found [here](https://github.com/hapijs/glue/blob/master/lib/index.js#L175) since those properties do not *need* to be kept? I'm having to rewrite the parsePlugin method to support hapi v17 anyways, and the Hoek clone is making it more complicated.

**Comment by csrl** [comment]
The reason the clone is there is in order to not modify the input arguments, and thus modify the caller's manifest.

The reason unknown fields are allowed, is so that any of the registration override fields allowed in https://hapijs.com/api#serverregisterplugins-options-callback are supported eg. 'once', 'select', 'routes'.   However, those technically aren't needed, since we only allow a single plugin per registration call anyway, so it is a redundant use case that we don't need to support.  So I'm ok with removing that support.

Whatever approach you take, ensure the inputs arguments are not modified (eg. the caller's manifest should be the exact object before and after calling compose.

**Comment by csrl** [comment]
I think our discussion on the PR supersedes this.

**Comment by WesTyler** [comment]
Agreed. Thanks!
